# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Irasas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemos_aprasymas', models.CharField(max_length=200)),
                ('kabineto_nr', models.CharField(max_length=30)),
                ('autorius', models.CharField(max_length=50)),
                ('reg_data', models.DateTimeField(verbose_name='Iraso data')),
                ('pab_data', models.DateTimeField(verbose_name='Atlikimo data')),
                ('komentaras', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irasas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Irasas')),
            ],
        ),
    ]
