# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irasas',
            name='pab_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Atlikimo data'),
        ),
    ]
