# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_auto_20180924_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipas',
            name='irasas',
        ),
        migrations.AddField(
            model_name='irasas',
            name='prob_tipas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Tipas'),
        ),
        migrations.AddField(
            model_name='tipas',
            name='prob_tipas',
            field=models.CharField(default='Nepasirinktas tipas', max_length=30),
            preserve_default=False,
        ),
    ]
